DEBUG = False
TWITTER_ACCESS_TOKEN = "FILL IN YOUR ACCESS TOKEN"
TWITTER_ACCESS_TOKEN_SECRET = "FILL IN YOUR ACCESS TOKEN SECRET"
TWITTER_CONSUMER_KEY = "FILL IN YOUR CONSUMER KEY"
TWITTER_CONSUMER_SECRET = "FILL IN YOUR CONSUMER SECRET"
ES_HOST = "some.hostname"
ES_PORT = 80
